### ISSUE TITLE
devices stop working randomly

### ISSUE THREAD

**Issue by tjarb** [harriedegroot/nl.hdg.mqtt#92]
Hi, the mqtt hub devices stop working randomly. Just rebooting homey or restarting MQTT related apps does not solve the issue. The only way to revive devices it to edit the device configuration (JSON) and add a spacebar hit. after saving the device comes back.

**Comment by PeterKawa** [comment]
Changing to these custom settings solved that one for me:
![Screenshot_20230921-184324_Homey.jpg](https://github.com/harriedegroot/nl.hdg.mqtt/assets/74005072/a9989686-ff09-46d4-8fcc-6510b8cee4d5)

**Comment by tjarb** [comment]
Hi @PeterKawa ,

Thank you for sharing your config. The difference between your custom config ans mine is the "include class", which I have disabled.

Could you please explain why this should resolve the issue?

**Comment by FredStang** [comment]
I tried @PeterKawa's solution but that did not solve the problem for me. The Mqtt still randomly stops working.

**Comment by FredStang** [comment]
@harriedegroot Do you think you will be able to have a look on this matter? 😃🙏

**Comment by wdool** [comment]
For me the same issue, also changing to custom settings did not result in a solution: 8ff67f77-7372-4bf1-aa16-3a661b2cf180
